# Generated by Django 4.2.6 on 2023-10-11 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('class_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('date', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3)),
                ('time_from', models.CharField()),
                ('time_to', models.CharField()),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=255)),
                ('class_room', models.IntegerField()),
                ('teacher', models.CharField(max_length=255)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schoolyear')),
            ],
        ),
    ]
